import Head from 'next/head';
import AppBar from '../components/AppBar';
import AboutMe from '../components/AboutMe';
import { Box, Paper } from '@mui/material';

export default function Home() {
  return (
    <Paper
      elevation={24}
      sx={{ pt: 10 }}
      style={{ width: '100%', height: 'auto' }}
      square>
      <Box>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <AppBar />
        <AboutMe />
      </Box>
    </Paper>
  );
}
